export default {
  API_ENDPOINT: process.env.REACT_APP_API_ENDPOINT,
  TOKEN_KEY: process.env.REACT_APP_TOKEN_KEY,
  API_USERNAME: process.env.REACT_APP_API_USERNAME,
  API_PASSWORD: process.env.REACT_APP_API_PASSWORD,
};